INSERT INTO `foods` VALUES (4064, 'Qủa dọc', '', 4, 0.36);
INSERT INTO `foods` VALUES (4065, 'Qủa me chua', 'Tamarind fruit, pulp raw', 4, 0.15);
INSERT INTO `foods` VALUES (4066, 'Rau bí', 'Pumpkin leaves', 4, 0.23);
INSERT INTO `foods` VALUES (4067, 'Rau câu khô', 'Dried seaweed', 4, 0.00);
INSERT INTO `foods` VALUES (4068, 'Rau câu tươi', 'Seaweed fresh', 4, 0.04);
INSERT INTO `foods` VALUES (4069, 'Rau diếp', 'Lettuce garden', 4, 0.10);
INSERT INTO `foods` VALUES (4070, 'Rau đay', 'Jute potherb', 4, 0.20);
INSERT INTO `foods` VALUES (4071, 'Rau giấp cá (diếp cá)', 'Wild plant', 4, 0.00);
INSERT INTO `foods` VALUES (4072, 'Rau giền cơm', 'Amaranth, spineless', 4, 0.00);
INSERT INTO `foods` VALUES (4073, 'Rau giền đỏ', 'Amaranth, sp. Red', 4, 0.38);
INSERT INTO `foods` VALUES (4074, 'Rau giền trắng', 'Amaranth, sp White', 4, 0.14);
INSERT INTO `foods` VALUES (4075, 'Rau húng', 'Basil sweet leaves, raw', 4, 0.20);
INSERT INTO `foods` VALUES (4076, 'Rau khoai lang', 'Sweet potato, leaves', 4, 0.05);
INSERT INTO `foods` VALUES (4077, 'Rau kinh giới', 'Sweet marjoram', 4, 0.16);
INSERT INTO `foods` VALUES (4078, 'Rau má rừng', 'Wild plant', 4, 0.00);
INSERT INTO `foods` VALUES (4079, 'Rau má (má mơ)', 'Wort, India penny', 4, 0.00);
INSERT INTO `foods` VALUES (4080, 'Rau mồng tơi', 'Malabar night shade, Vinespinach, Ceylon spinach', 4, 0.17);
INSERT INTO `foods` VALUES (4081, 'Rau mùi', 'Coriander', 4, 0.15);
INSERT INTO `foods` VALUES (4082, 'Rau mùi tàu', 'Parsley, curley', 4, 0.20);
INSERT INTO `foods` VALUES (4083, 'Rau muống', 'Swamp cabbage, water spinach, water convol', 4, 0.37);
INSERT INTO `foods` VALUES (4084, 'Rau muống khô', 'Water spinach, dried', 4, 0.00);
INSERT INTO `foods` VALUES (4085, 'Rau ngổ', 'Limnophila aromatic', 4, 0.29);
INSERT INTO `foods` VALUES (4086, 'Rau ngót', 'Sauropus, sp. leaves', 4, 0.23);
INSERT INTO `foods` VALUES (4087, 'Rau ngót khô', 'Sauropus, dried', 4, 0.00);
INSERT INTO `foods` VALUES (4088, 'Rau răm', 'Polygonum odoratum', 4, 0.25);
INSERT INTO `foods` VALUES (4089, 'Rau rút', 'Neptunia, dismanthus', 4, 0.55);
INSERT INTO `foods` VALUES (4090, 'Rau sà lách', 'Lettuce, garden asparagus', 4, 0.10);
INSERT INTO `foods` VALUES (4091, 'Rau sam', 'Purslane, common', 4, 0.00);
INSERT INTO `foods` VALUES (4092, 'Rau sắng (chùa Hương)', 'Perfume pagoda wild plant', 4, 0.40);
INSERT INTO `foods` VALUES (4093, 'Rau tàu bay', 'Gynura crepidioides', 4, 0.00);
INSERT INTO `foods` VALUES (4094, 'Rau thơm', 'Mint leaves', 4, 0.25);
INSERT INTO `foods` VALUES (4095, 'Sấu xanh', 'Dracontomelum fruit, unripe, raw', 4, 0.35);
INSERT INTO `foods` VALUES (4096, 'Su hào', 'Kohlrabi', 4, 0.22);
INSERT INTO `foods` VALUES (4097, 'Su hào khô', 'Dried kohlrabi', 4, 0.00);
INSERT INTO `foods` VALUES (4098, 'Su su, quả', 'Chayote, fruit raw', 4, 0.20);
INSERT INTO `foods` VALUES (4099, 'Súp lơ trắng', 'Cauliflower, white', 4, 0.40);
INSERT INTO `foods` VALUES (4100, 'Súp lơ xanh', 'Cauliflower, green', 4, 0.39);
INSERT INTO `foods` VALUES (4101, 'Thìa là', 'Dill', 4, 0.25);
INSERT INTO `foods` VALUES (4102, 'Tía tô', 'Balm-mint, garden- balm', 4, 0.20);
INSERT INTO `foods` VALUES (4103, 'Tỏi ta', 'Garlic bulbs', 4, 0.20);
INSERT INTO `foods` VALUES (4104, 'Tỏi tây (cả lá)', 'Chinese Leek, Onion fragrant', 4, 0.20);
INSERT INTO `foods` VALUES (4105, 'Trám đen chín', 'Variety of canarium', 4, 0.50);
INSERT INTO `foods` VALUES (4106, 'Trám xanh sống, trám trắng', 'Chinese olive', 4, 0.34);
INSERT INTO `foods` VALUES (4107, 'Xương sông', 'Edible herbaceous plant', 4, 0.10);
INSERT INTO `foods` VALUES (4108, 'Cà chua muối', 'Tomato, pickled', 4, 0.05);
INSERT INTO `foods` VALUES (4109, 'Cà muối nén', 'Eggplant, garden, brinjan; aubergine, pickled', 4, 0.05);
INSERT INTO `foods` VALUES (4110, 'Cà muối sổi', 'Eggplant, garden, brinjan; aubergine, pickled', 4, 0.05);
INSERT INTO `foods` VALUES (4111, 'Dưa cải bắp', 'Cabbage Chinese, pickled', 4, 0.05);
INSERT INTO `foods` VALUES (4112, 'Dưa cải bẹ', 'Mustard green, pickled', 4, 0.05);
INSERT INTO `foods` VALUES (4113, 'Dưa cải sen', 'Rape bird, pickled', 4, 0.05);
INSERT INTO `foods` VALUES (4114, 'Dưa chuột muối', 'Cucumber, pickled', 4, 0.05);
INSERT INTO `foods` VALUES (4115, 'Dưa giá (đậu xanh)', 'Mung bean sprouts, pickled', 4, 0.00);
INSERT INTO `foods` VALUES (4116, 'Hành củ muối', 'Onion, pickled', 4, 0.30);
INSERT INTO `foods` VALUES (4117, 'Kiệu muối', 'Onion shallot, scallion, pickled', 4, 0.30);
INSERT INTO `foods` VALUES (4118, 'Nhút (muối từ mít non, ngọn đậu xanh non...)', 'Mix pickled from young jack fruit', 4, 0.00);
INSERT INTO `foods` VALUES (4119, 'Men bia khô', "Brewer's yeast, fried", 4, 0.00);
INSERT INTO `foods` VALUES (4120, 'Men bia tươi ', "Baker's yeast, fresh", 4, 0.00);
INSERT INTO `foods` VALUES (4121, 'Mộc nhĩ', "Jew's ear, Juda's ear, dried, Wood-ear, Tender variety", 4, 0.10);
INSERT INTO `foods` VALUES (4122, 'Nấm hương khô', 'Mushroom Chinese, dried', 4, 0.10);
INSERT INTO `foods` VALUES (4123, 'Nấm hương tươi', 'Mushroom, Chinese, raw', 4, 0.25);
INSERT INTO `foods` VALUES (4124, 'Nấm mỡ (nấm tây)', 'Mushroom', 4, 0.10);
INSERT INTO `foods` VALUES (4125, 'Nấm rơm', 'Mushroom, straw', 4, 0.10);
INSERT INTO `foods` VALUES (4126, 'Nấm thường tươi', 'Mushroom, common', 4, 0.25);
INSERT INTO `foods` VALUES (100001, 'Gạo nếp cái', 'Glutinous rice, milled', 1, 0.00);
